Repository markdownlint/markdownlint, pull requests merged in 2019-10, with the labels that each got.

#275 Add issue templates to help standardize requests
  .github/ISSUE_TEMPLATE/BUG_TEMPLATE.md
  .github/ISSUE_TEMPLATE/DESIGN_PROPOSAL.md
  .github/ISSUE_TEMPLATE/ENHANCEMENT_REQUEST.md
  .github/ISSUE_TEMPLATE/RULE_REQUEST.md
  CONTRIBUTING.md
Labels: documentation

#267 Update kramdown dependency to major ver 2
  mdl.gemspec
Labels: waiting on submitter

#239 Fix for Kramdown tables of contents
  lib/mdl/rules.rb
Labels: bug, fix, waiting on submitter

#276 Add a pull request template to help contributors
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
Labels: documentation
